# Generated by Django 4.1.7 on 2024-02-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("techblog", "0003_alter_comment_created_at_alter_postfield_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postfield",
            old_name="body",
            new_name="content",
        ),
    ]
