# Generated by Django 4.1.7 on 2024-02-09 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techorders", "0011_alter_comments_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=50, verbose_name="Firstname"),
                ),
                ("lastname", models.CharField(max_length=50, verbose_name="Lastname")),
                ("phone", models.CharField(max_length=50, verbose_name="Phone no")),
                ("email", models.EmailField(max_length=50, verbose_name="Email")),
                ("message", models.TextField(verbose_name="message")),
                ("date", models.DateField(auto_now_add=True, verbose_name="date sent")),
            ],
        ),
        migrations.RemoveField(
            model_name="comments",
            name="name",
        ),
        migrations.AddField(
            model_name="comments",
            name="firstname",
            field=models.CharField(max_length=50, null=True, verbose_name="Firstname"),
        ),
        migrations.AddField(
            model_name="comments",
            name="lastname",
            field=models.CharField(max_length=50, null=True, verbose_name="Lastname"),
        ),
        migrations.AlterField(
            model_name="comments",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 9, 15, 48, 0, 755140),
                verbose_name="date posted",
            ),
        ),
    ]
