# Generated by Django 4.1.7 on 2024-02-09 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techorders", "0012_contact_remove_comments_name_comments_firstname_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="comments",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 9, 15, 49, 44, 65073),
                verbose_name="date posted",
            ),
        ),
    ]
