# Generated by Django 4.1.7 on 2024-02-17 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techorders", "0013_alter_contact_options_alter_comments_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments",
            options={
                "ordering": ["date"],
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
            },
        ),
        migrations.AlterField(
            model_name="comments",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 17, 0, 32, 14, 873516),
                verbose_name="date posted",
            ),
        ),
    ]
