# Generated by Django 4.1.7 on 2024-02-17 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techorders", "0014_alter_comments_options_alter_comments_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Firstname"
                    ),
                ),
                (
                    "lastname",
                    models.CharField(max_length=50, null=True, verbose_name="Lastname"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="senders email"),
                ),
                ("comments", models.TextField(max_length=500)),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 2, 17, 1, 12, 43, 672539),
                        verbose_name="date posted",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-date"],
            },
        ),
        migrations.DeleteModel(
            name="Comments",
        ),
    ]
