# Generated by Django 4.1.7 on 2024-02-17 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techorders", "0015_reviews_delete_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviews",
            old_name="comments",
            new_name="review",
        ),
        migrations.AlterField(
            model_name="reviews",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 17, 9, 20, 57, 721247),
                verbose_name="date posted",
            ),
        ),
    ]
