# Generated by Django 4.1.7 on 2024-04-14 20:27

import datetime
from django.db import migrations, models
import techapps.techorders.models


class Migration(migrations.Migration):

    dependencies = [
        ("techorders", "0016_rename_comments_reviews_review_alter_reviews_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=50)),
                (
                    "img_url",
                    models.ImageField(upload_to=techapps.techorders.models.upload_to),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Firstname"
                    ),
                ),
                (
                    "lastname",
                    models.CharField(max_length=50, null=True, verbose_name="Lastname"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="senders email"),
                ),
                ("message", models.TextField(max_length=500)),
                ("positive", models.BooleanField(default=False, verbose_name="")),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="date posted"
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-date"],
            },
        ),
        migrations.DeleteModel(
            name="Reviews",
        ),
    ]
